### ISSUE TITLE
SetPixel method from original C++ binding?

### ISSUE THREAD

**Issue by marjinal1st** [Sonkun/python-sfml#105]
I'm trying to convert [this SFML](https://github.com/LaurentGomila/SFML/wiki/Source:-Particle-System#particlecpp) example to pysfml, but stuck in a method.

Original is:

```cpp
m_image.SetPixel( (int)(*it)->pos.x, (int)(*it)->pos.y, m_transparent );
```

But I can't find any "SetPixel" or equivalent method for sf.Image class.

Any ideas?

**Comment by dindoun** [comment]
image=sf.Image.from_file(nomIMAGE1)
image[x,y]=sf.Color(255,255,255,255)

**Comment by Sonkun** [comment]
@dindoun: thank you
