### ISSUE TITLE
Can't Build on Ubuntu 14.04

### ISSUE THREAD

**Issue by marjinal1st** [Sonkun/python-sfml#106]
Tried to build the latest code on Ubuntu 14.04. 

If I use **Cython 0.20** it gives this error:

https://gist.github.com/marjinal1st/8c4c700c84ae33185b96

If I use **Cython 0.21**, it gives this error:

https://gist.github.com/marjinal1st/03f9e6daeaeb3f2aafc7

Any ideas?

**Comment by Sonkun** [comment]
Pull request merged, problem solved!
