### ISSUE TITLE
Bug with 'MouseWheelEvent' events in wrap_event (windows.pyx)

### ISSUE THREAD

**Issue by yoyonel** [Sonkun/python-sfml#115]
Build informations:
- OS: Mint 17 x64
- Python: Python 2.7.6
- GCC (x86_64-linux-gnu-gcc): gcc version 4.8.4 
- Cython: Cython version 0.22
- SFML: /usr/local/lib/libsfml-system.so -> libsfml-system.so.2.3 (get from GIT)

the bug appears when using the mouse wheel:
python-sfml/examples/opengl$ python opengl.py 
Traceback (most recent call last):
  File "opengl.py", line 51, in <module>
    for event in window.events:
  File "sfml/window.pyx", line 799, in events_generator (src/sfml/window.cpp:14878)
  File "sfml/window.pyx", line 161, in sfml.window.wrap_event (src/sfml/window.cpp:2980)
UnboundLocalError: local variable 'event' referenced before assignment

In windows.pyx (@130), you have:
elif p.type == sf.event.MouseWheelMoved:
        event = MouseWheelEvent.__new__(MouseWheelEvent)
but ... seems to not working well ...

Any idea to fix this ?
Thx in advance.

**Comment by bobbysoon** [comment]
I can confirm this.

**Comment by TankOs** [comment]
Confirmed on me side as well.

**Comment by Sonkun** [comment]
Thank you for reporting this bug (and sorry I took so long to fix it). This was introduced when SFML added a new event type *MouseWheelScrolled*.

I'm going to add proper support for MouseWheelScrolled in the develop branch (and will also refactor some ugly things I did years ago with how pySFML handles SFML events :p)

**Comment by TankOs** [comment]
Good to see you back, Sonkun :)

**Comment by captnfab** [comment]
Hi,

It looks like this bug happens again. Here is an error raised by the script below:

    Traceback (most recent call last):
      File "./bug.py", line 13, in <module>
        for event in w.events:
      File "src/sfml/window.pyx", line 797, in events_generator (src/sfml/window.cpp:14768)
      File "src/sfml/window.pyx", line 161, in sfml.window.wrap_event (src/sfml/window.cpp:3324)
    UnboundLocalError: local variable 'event' referenced before assignment

Complete script:

    #!/usr/bin/env python3
    
    import sfml
    
    if __name__=="__main__":
        w = sfml.graphics.RenderWindow(sfml.window.VideoMode(800,800), "Bug")
        w.framerate_limit = 60
        v = sfml.graphics.View()
        view = sfml.graphics.View()
        view.size = w.size
    
        while w.is_open:
            for event in w.events:
                if type(event) is sfml.window.CloseEvent:
                    w.close()
                elif type(event) is sfml.window.KeyEvent:
                    if event.code == sfml.window.Keyboard.ESCAPE:
                        w.close()
            w.clear(sfml.graphics.Color.BLUE)
            w.display()

I'm using python3-sfml package version 2.2~git20150611.196c88+dfsg-3+b1 from Debian Stretch.

**Comment by captnfab** [comment]
Ok, it looks like it "happens again" in the *past* since debian package version is a 2.2

**Comment by captnfab** [comment]
I confirm there is no such problem with the current 2.3 version. Sorry for the noise.
