### ISSUE TITLE
Provide ability to specify custom include/lib folders during setup.py build

### ISSUE THREAD

**Issue by firefly2442** [Sonkun/python-sfml#121]
On Linux, I don't have SFML installed system-wide so `python setup.py build` did not work for me because it couldn't find the appropriate include headers.  It would be nice to perhaps adjust the `setup.py` script to take optional folder locations which could be appended and used during the build process.  I tried adjusting the `setup.py` script to take parameters but I wasn't sure how to get it to work and not break the abilities of distutils.

I was able to get around the issue by doing the following:

```
CFLAGS="-I /home/user/installs/SFML/include" LDFLAGS="-L /home/user/installs/SFML/lib" python setup.py build
```

**Comment by firefly2442** [comment]
And to get the generated build of the libraries to be used instead of installing system wide:

    export PYTHONPATH=$PYTHONPATH:/home/user/src/python-sfml/build/lib.linux-x86_64-2.7/
    python demo.py

**Comment by Sonkun** [comment]
This is done with `--include-didrs` and `--library-dirs` flags. Example `python setup.py build_ext --include-dirs foo/bar --library-dirs bar/foo`. Once compiled and installed (for instance, in a virtualenv), use LD_LIBRARY_PATH for Python to find SFML libs.
