### ISSUE TITLE
Undefined symbol: compile against latest version of SFML

### ISSUE THREAD

**Issue by firefly2442** [Sonkun/python-sfml#122]
I compiled pysfml with the fix PR #120.  I'm also trying this with the latest development version of SFML (which might be the problem).  There were no compile errors during `setup.py`.  I get the following error upon running an example:

    user@machine:~/src/python-sfml/examples/pong$ python pong.py 
    Traceback (most recent call last):
      File "pong.py", line 6, in <module>
        from sfml import sf
      File "/home/user/src/python-sfml/build/lib.linux-x86_64-2.7/sfml/__init__.py", line 1, in <module>
        import sfml.system
    ImportError: /home/user/src/python-sfml/build/lib.linux-x86_64-2.7/sfml/system.so: undefined symbol: _Z14Time_div_floatN2sf4TimeEf

I've never used Cython before, what are some things I can do to attempt to diagnose this issue?

**Comment by jcowgill** [comment]
@Erwhann-Rouge

Ok so we've found the underlying problem in #118 :)

I think `hacks.cpp` contains this undefined function, but when the code was implemented in d8b341f0b966525168e17d643575f58afda92895, someone forgot to push it.

As a temporary workaround (I think) you can revert these commits:
aea613a2ccb88f5f030510a32bcfecbfcdc0200b and then d8b341f0b966525168e17d643575f58afda92895

**Comment by firefly2442** [comment]
Ahha, thank you.  Well, I tried your suggestion and here's what I found.

* checkout master
* revert aea613a2ccb88f5f030510a32bcfecbfcdc0200b and d8b341f0b966525168e17d643575f58afda92895
* rebuild
* now getting the following error for "pong" (and similar error for "spacial_music")

```
user@machine:~/src/python-sfml/examples/pong$ python pong.py Traceback (most recent call last):
File "pong.py", line 29, in <module> left_paddle.origin = paddle_size / 2
TypeError: unsupported operand type(s) for /: 'sfml.system.Vector2' and 'int'
```

The "sound" demo works though.  I think it's working, it just might have a couple lingering issues.  I'll play with it some more.

**Comment by feinstaub** [comment]
Hi I have the same problem but I am not able to revert the commits:

```
git clone git://github.com/Sonkun/python-sfml.git

git revert aea613a

git revert -n d8b341f
error: could not revert d8b341f... Implemented mul and div operators in Time class (#38)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
```

**Comment by jcowgill** [comment]
I don't think you need to revert those commits anymore with the current master branch. I did need this patch though:

```diff
--- a/setup.py
+++ b/setup.py
@@ -94,7 +94,7 @@ else:
 
 system = extension(
     'system',
-    ['system.pyx', 'error.cpp', 'hacks.cpp'],#, 'NumericObject.cpp'],
+    ['system.pyx', 'error.cpp', 'hacks.cpp', '../NumericObject.cpp'],
     ['sfml-system'])
 
 window = extension(
@@ -104,7 +104,7 @@ window = extension(
 
 graphics = extension(
     'graphics',
-    ['graphics.pyx', 'DerivableRenderWindow.cpp', 'DerivableDrawable.cpp'],
+    ['graphics.pyx', 'DerivableRenderWindow.cpp', 'DerivableDrawable.cpp', '../NumericObject.cpp'],
     ['sfml-system', 'sfml-window', 'sfml-graphics'])
 
 audio = extension(
```

**Comment by Sonkun** [comment]
Actually, I'm working on that one.

Compiling NumericObject.cpp twice results in duplicated symbols. The proper solution is to have these symbols only once in the system module extension but they aren't loaded from the graphics module extension on Linux. On Windows it works fine.

I finally found a solution to this. Will be back shortly.

**Comment by Sonkun** [comment]
In the past I had conflicting symbols (and other bugs) when porting Thor to Python but I cannot reproduce these problems... Event compiling NumericObject.cpp twice didn't work for me in the past but now everything appears to work very well. I wouldn't have left the repository in a uncompilable state if I knew this was viable workaround.

However, later, if I come across any symbol problems, one way to compile NumericObject.cpp only once and get it reused in the graphics module is to link against the system.cpython-3.4.so directly. The code would look like this:
```
graphics.extra_link_args.append('/home/sonkun/Workspace/python-sfml/build/lib.linux-x86_64-3.4/sfml/system.cpython-34m.so')
graphics.extra_link_args.append('-Wl,-rpath,'+'/home/sonkun/Workspace/python-sfml/build/lib.linux-x86_64-3.4/sfml/')```

Where graphics is the Extension object in setup.py.

**Comment by Sonkun** [comment]
Here we go, in Thor, in the math and vectors module which use `PyVector2Object`, I have to link against the `system.cpython-34m.so`, I cannot simply reship NumericObject.cpp and rebuild it. So at some point, I'll rework this.

Anyway, duplicating NumericObject.cpp was a good idea, thank you for reporting this (known) bug and coming up with a fix.
