### ISSUE TITLE
Is http://www.python-sfml.org/ dead?

### ISSUE THREAD

**Issue by egorpuzyrev** [Sonkun/python-sfml#124]
Seems http://www.python-sfml.org/ is dead. I tried just to open it, also tried to use proxy, but in any case it shows me "Server not found" error.

**Comment by Sonkun** [comment]
Oh shit, I forgot to renew the domain name. I just checked and I need to wait a few days before I can reorder it. It's going to be fixed as soon as it's available for registration.

Thanks for reporting that.

**Comment by daikazoku** [comment]
Do you have an IP or a temporary mirror or anything like that? :)

**Comment by egorpuzyrev** [comment]
Try to look at Google saved copies. They are not perfect, but still can be helpful.

**Comment by iago-lito** [comment]
Is this error related?

    $ git clone --recursive git://github.com/Sonkun/python-sfml.git
        Cloning into 'python-sfml'...
        remote: Counting objects: 6119, done.
        remote: Total 6119 (delta 0), reused 0 (delta 0), pack-reused 6119
        Receiving objects: 100% (6119/6119), 37.02 MiB | 462.00 KiB/s, done.
        Resolving deltas: 100% (3747/3747), done.
        Checking connectivity... done.
        Submodule 'add-ons/sfemovie' (git@github.com:Sonkun/python-sfemovie.git) registered for path 'add-ons/sfemovie'
        Submodule 'add-ons/thor' (git@github.com:Sonkun/python-thor.git) registered for path 'add-ons/thor'
        Cloning into 'add-ons/sfemovie'...
        Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
        Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        Clone of 'git@github.com:Sonkun/python-sfemovie.git' into submodule path 'add-ons/sfemovie' failed
 
.. or should I open another issue? .. or have I done anything wrong?

**Comment by jcowgill** [comment]
@iago-lito That issue is unrelated to this and happens because you don't have a github SSH key and the `.gitmodules` file uses SSH clone URLs (which is a bug IMO).

You can either add your SSH key to github, or try this:
```
git clone https://github.com/Sonkun/python-sfml.git
cd python-sfml
git config submodule.add-ons/sfemovie.url https://github.com/Sonkun/python-sfemovie.git
git config submodule.add-ons/thor.url https://github.com/Sonkun/python-thor.git
git submodule update
```

**Comment by iago-lito** [comment]
It works fine with a ssh key indeed. Thank you :)

Should I open an issue at [sfemovie](https://github.com/Sonkun/python-sfemovie)?

**Comment by Sonkun** [comment]
Given OVH hasn't released the domain name, I still cannot renew it... Will make a temporary copy now.

@iago-lito , this issue isn't related to sfemovie, so there's not need to open an issue at sfemovie. I will look into that now.

**Comment by Sonkun** [comment]
@iago-lito : I updated the .gitmodules, if you retry the command line, that should pass now. Thanks for reporting.

I need to reset my OVH account pasword to get a copy of the website but it says "unable to start the service" so I guess I have to wait. Anyway, I already set up the temporary website, expect it to be available at http://pysfml.sonkun-dev.net/ in a few hours.

Thanks for waiting.

**Comment by Sonkun** [comment]
Finally, I could renew the domain name.
