### ISSUE TITLE
GUI libs for this wrapper

### ISSUE THREAD

**Issue by egorpuzyrev** [Sonkun/python-sfml#125]
Tutorial about integrating pySFML into PyQt4 is too poor. Also, there is no any another GUI libs for integrate with this wrapper, looking over internet. So, the questions are:
1) could you improve PyQt4 tutorial (add events processing at least)?
2) maybe anybody know, is there any other good-working GUI lib?

**Comment by TankOs** [comment]
> 1) could you improve PyQt4 tutorial (add events processing at least)?

This of course fits to everything, but especially very much in this case: What about contributing a better documentation for integrating it yourself?

**Comment by Sonkun** [comment]
Yes, trying out PyQt yourself and sharing your experience on the wiki is a great idea. There shouldn't be any major issue and if anything needs to be modified in the source code of pySFML, we can work on that.

That said, it would be great if someone port SFGUI to Python. At this time, these bindings are complete enough to achieve this, in fact I almost finished to port the entire Thor framework (check recent commits [here](https://github.com/PySFML/python-thor)) and soon it will become a reference for bindings to other SFML-based libraries.

By the way, soon I will release 2.3.2 with a rewritten website and pyThor alongside. It's going to be more maintained with buildbots and unit tests from now on!
