### ISSUE TITLE
text adding extra character at the begging of string

### ISSUE THREAD

**Issue by katoum** [Sonkun/python-sfml#130]
When using text, all my strings have an extra character that shows as a square when rendered. I've attached my code and a the output.
![text adding extra character](https://cloud.githubusercontent.com/assets/19431509/15362271/194b8b84-1ceb-11e6-9d23-48c94938f253.PNG)

**Comment by Sonkun** [comment]
hello, yes, that's a known bug.

this is one of the last 3 things I need to do before I release PySFML 2.3.2 and the updated website. This will disappear as you start using the upcoming version. This is going to be fixed shortly.

**Comment by katoum** [comment]
Thanks, I will be looking forward to it!

**Comment by alkhimey** [comment]
I am getting this bug as well. What are the chances that any of you know a workaround for this?

**Comment by Sonkun** [comment]
This is fixed. Thanks for reporting!
