### ISSUE TITLE
sfml.Text.string getter returns always empty string

### ISSUE THREAD

**Issue by wojtex** [Sonkun/python-sfml#131]
`sfml.Text.string` returns always empty string although it contains some text.

Platform: Windows 7 Professional
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:37:12) [MSC v.1600 32 bit (Intel)] on win32
Python-SFML installed using installer from [python-sfml.org](http://python-sfml.org/download.html) (file: [pySFML-1.3.0.win32-py3.3.exe](http://python-sfml.org/1.3/downloads/pySFML-1.3.0.win32-py3.3.exe))

Example:

``` python
import sfml as sf

window = sf.RenderWindow(sf.VideoMode(640, 480), "test")

text = sf.Text('Initial')                                                         
font = sf.Font.from_file('C:\\Windows\\Fonts\\arial.ttf')                         
text.font = font                                                                  
text.character_size = 40                                                          
text.position = (100, 100)                                                        
text.color = sf.Color.BLACK                                                       

window.clear(sf.Color.WHITE)
window.draw(text)
window.display()

print('Initial:  "'+text.string+'"')
sf.sleep(sf.seconds(3))

text.string = 'Modified'

window.clear(sf.Color.WHITE)
window.draw(text)
window.display()

print('Modified: "'+text.string+'"')
sf.sleep(sf.seconds(3))

window.close()
```

This draws texts `Initial` and then `Modified` but prints to the console:

```
Initial:  ""
Modified: ""
```

**Comment by Sonkun** [comment]
Please work with the latest version of these bindings. The old ones were very buggy. Your code works well with development version. Good luck.
