### ISSUE TITLE
Importation fails due to undefined symbol: __cpu_model

### ISSUE THREAD

**Issue by iago-lito** [Sonkun/python-sfml#134]
After having solved problem #132 (so reverted to commit 8d2f0a7), I cannot load `pysfml` anymore, due to an apparent linkage error:

    Python 3.5.2 (default, Jul  5 2016, 11:33:36) 
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sfml
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.5/dist-packages/sfml/__init__.py", line 3, in <module>
        import sfml.graphics
    ImportError: /usr/local/lib/libsfml-graphics.so.2.3: undefined symbol: __cpu_model
    >>>

This is Debian 9 (stretch) speaking, up-to-date, with the latest version of SFML compiled from its [github repo](https://github.com/SFML/SFML). Do you think the problem comes from `pysfml` or from `SFML` library?

**Comment by jcowgill** [comment]
It's a bug in gcc 5 (fixed in gcc 6). See:

https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899
nothings/stb#280

**Comment by iago-lito** [comment]
How deep! Thanks. Let me try gcc 6 out and keep you udpate Ô.Ô
