### ISSUE TITLE
Segfault when accessing transform position

### ISSUE THREAD

**Issue by fazjaxton** [Sonkun/python-sfml#136]
I am getting a `Segmentation fault (core dumped)` error on code that works on 1.5.  I have narrowed it down to the following test case:

```
from sfml import sf

class Test (sf.TransformableDrawable):
    def __init__(self):
        pass

t = Test()
print t.position
```

Attempting to access the transform position causes the segfault.  I am running latest python-sfml from git with SFML libs from Ubuntu 16.04.

**Comment by Sonkun** [comment]
You're not initializing sf.TransformableDrawable with __init__() in the construction.

Also, make sure you use latest version. And checkout the `fix-transformable-drawable` branch. It's now possible to subclass from both sf.Drawable and sf.Transformable, leaving sf.TransformableDrawable obsolete.
