### ISSUE TITLE
Incorrect video mode on Ubuntu 15.10

### ISSUE THREAD

**Issue by riteme** [Sonkun/python-sfml#138]
Hi, I have just updated to the latest version on the master branch by cloning this repo, and I found that something isn't correct:

![800x600 window](http://git.oschina.net/riteme/blogimg/raw/master/other/bug-sfml2.3-python3.5-ubuntu-15.10.png)

This is one of my small projects written in Python3 with Python3-SFML. Before upgrading, ths displaying is correct, and then it becomes something above.
I have tried different resolutions and it seems that the view is always smaller than the window size, and everything becomes scaled.

I'm using Python 3.5.0 / Cython3 0.23.3 / GCC 5.2.1 / SFML 2.3.2 on Ubuntu 15.10 x64 machine.

**Comment by Sonkun** [comment]
May be a bug in latest version of pySFML,I dont have time to investigate
now, can you fix it by setting a custom view?

**Comment by riteme** [comment]
Yeah, I found that resetting `window.view` by hand is correct. Maybe there is something wrong with window initializations.

**Comment by Sonkun** [comment]
Thanks for reporting it, it's fixed now.
