### ISSUE TITLE
Shape position bug (important?)

### ISSUE THREAD

**Issue by Ryozuki** [Sonkun/python-sfml#143]
```python
rectangle = RectangleShape()
rectangle.size = (50, 50)
rectangle.outline_color = sf.Color.RED
rectangle.outline_thickness = 5
rectangle.position = window.size / 2
rectangle.origin = rectangle.size / 2
```

So, theoretically this should center the rectangle into the center of the window, but it isn't why?

Edit:
This workaround fixes it: `window.view.reset(sf.Rect(size=window.size))`

Might be related to https://github.com/Sonkun/python-sfml/issues/138

**Comment by Sonkun** [comment]
Yes it was related to #138 which is now fixed. Thanks for reporting!
