### ISSUE TITLE
Inconsistent position types

### ISSUE THREAD

**Issue by PythonFanboy** [Sonkun/python-sfml#146]
I'm just starting with pySFML, but found some inconsistencies that make it hard to use or understand.

`sf.Rect()` uses `left` and `right`, but there is no `.x` nor `.y`,

`Sprite.position` and all shapes' positions are tuples (?) or Vector2, don't know really, but their `.x/y` attributes can't be modified.

`Window` has `.size.x/y`, but no `.width/height`.

`Texture` has `.size`, `.width` and `.height`, while `Sprite` doesn't have any of them.

`View` has no position (?), but can be moved via `.move()`. It has `.size`, but no `width/height`.

Could anyone clarify anything of the above?

**Comment by Sonkun** [comment]
You're using a old version of these bindings. Yes this is plain stupid. With last version you do.

```
r = sf.Rect()
r.left
r.top
r.width
r.height
```

In recent version, all functions, methods and properties accept both tuple or Vector2. But they return Vector2 objects. On your side, favor tuples for readability, if you don't doo arithmetic operations (you can nicely unpack them with `x, y = position`), use Vector2 if you do arithmetic. 

The 'problem' with Vector2 is that they're mutable unlike tuples. This is not a problem, just an aspect of the Python language you must work with.

As for the rest, it now follows the original C++ API. By the way, I will soon upload an updated version of the documentation. I'm half way thought. 

Good luck! If you use Windows, you can download installers on website
