### ISSUE TITLE
Consider adding pyrokit to the add-on list (GUI engine)

### ISSUE THREAD

**Issue by shackra** [Sonkun/python-sfml#69]
Hello! :)

I've been doing some research on [LibRocket](http://librocket.com/) for Python. LibRocket **is a HTML/CSS GUI engine**, I saw some videos and it looks very cool. I decided to see if some one has done some work on porting LibRocket to python, fortunately, there is one project called [Pyrokit](https://bitbucket.org/skewedaspect/pyrokit), such project started the last year.

I see that **they integrated python-sfml render to their bindings** (as LibRocket did with Laurent's SFML since libRocket 1.2.1), even there is a [example test](https://bitbucket.org/skewedaspect/pyrokit/src/e8f79d8fafe2/examples/test-sfml.py?at=default), So, **I'll strongly suggest that consider adding Pyrokit as an add-on for python2-sfml instead of any other GUI out there.**

After all, there is some work done already, so, starting to maintain Pyrokit wouldn't be a big deal, unless you don't know Cython as it is in my case :) (grrr!)

So, what you say guys? :)

![librocket_yay](https://f.cloud.github.com/assets/1055216/125675/c6cb33a2-6f1c-11e2-9847-f6c8e7237c2f.png)

Yup, [Pyrokit and Panda3D](http://www.panda3d.org/forums/viewtopic.php?t=10062&postdays=0&postorder=asc&start=0)

**Comment by Sonkun** [comment]
If the libRocket project is still there and worth being ported, I encourage people to port it :) The PyThor project is a good reference to port C++ libraries that coerce nice with the PySFML bindings.
