### ISSUE TITLE
Unable to resize window ("attribute 'size' is not writable)

### ISSUE THREAD

**Issue by llacom** [Sonkun/python-sfml#74]
Hi, and thanks very much for these bindings !

I'm unable to change the size of the window "on the fly" :

``` python
import sfml as sf
w = sf.RenderWindow(sf.VideoMode(640,480), "MPlayer")
w.size = (100, 100)
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-138-332f5fe894e4> in <module>()
----> 1 w.size = (100, 100)
AttributeError: attribute 'size' of 'sfml.graphics.RenderWindow' objects is not writable

I tried using w.position which seems to be similar to w.size and it worked as expected.
I'm using python 3.3.1, SFML 2.0.1 and the git version of pysfml

**Comment by Sonkun** [comment]
Really.. I thought it was fixed years ago.
