### ISSUE TITLE
Provide tutorial for standalone packaging

### ISSUE THREAD

**Issue by svenstaro** [Sonkun/python-sfml#78]
Currently it would appear to be rather hard to create a standalone python executable using python-sfml due to the way cython works. I could not figure this out with cx_freeze and pyinstaller. Perhaps you can provide a tutorial?

**Comment by Sonkun** [comment]
Given the implementation of sfml.Graphcis.Rect changed, I wonder if that issue still persists... Anyway, I started to rework (and automate) the compilation/installation process on each platforms, and started to experiment with pyInstaller, py2exe and cx_Freeze. Results: except some difficulties to install these tools with Python 3.5, they appear to work well with pySFML. The next step is to experiment with a program that mix both pySFML and pyThor and I will provide a document that shows the steps to follow.

This issues tracker is no longer used for todo tasks. This task has been added to the remaining tasks list on the website.
